Context
maver1cus/junior-course-boilerplate pull request #5
Opened 2021-03-31 08:11 UTC by maver1cus

2021-03-31 08:39 UTC, vislogurov requested changes

2021-03-31 08:39 UTC, vislogurov commented on src/components/app/app.jsx
> +      selectedCategories: this.getAllCategories(products)
Если это reset-метод, то почему тут products, а не пустой массив?

2021-03-31 08:39 UTC, vislogurov commented on src/components/app/app.jsx
> +
Получается, что при ресете урл c выбранными категорями не ресетнется

2021-03-31 08:39 UTC, vislogurov commented on src/components/button/button.jsx
> +    <button
Хорошо бы указать type у кнопки. Иначе браузер сам решит, что делает эта кнопка, и такое поведение может отличаться от того, что задумал разработчик)

2021-03-31 08:39 UTC, vislogurov commented on src/components/app/app.jsx
> +      : this.getAllCategories(this.props.products)
Разве getAllCategories принимает какой то аргумент? Судя по сигнатуре метода нет. Ты же потом внутри метода непосредственно читаешь `const categories = this.props.products... итд`

2021-04-01 06:51 UTC, maver1cus commented on src/components/app/app.jsx
> +      selectedCategories: this.getAllCategories(products)
Он ресетит фильтры, а массив в products содержит все товыры из json, для вычесления дефолтных фильтров

2021-04-01 06:51 UTC, maver1cus commented on src/components/app/app.jsx
> +
done

2021-04-01 06:51 UTC, maver1cus commented on src/components/button/button.jsx
> +    <button
done

2021-04-01 06:51 UTC, maver1cus commented on src/components/app/app.jsx
> +      : this.getAllCategories(this.props.products)
done

2021-04-09 09:52 UTC, merged